# Generated by Django 4.2.7 on 2026-05-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('nid_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('FD', 'Fixed Deposit Account')], max_length=20)),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('photograph', models.ImageField(upload_to='applicant_photos/')),
                ('nid_copy', models.FileField(upload_to='nid_copies/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('nominee_name', models.CharField(max_length=200)),
                ('nominee_relation', models.CharField(max_length=100)),
                ('nominee_nid', models.CharField(max_length=20)),
                ('nominee_mobile', models.CharField(max_length=15)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.accountapplication')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['nid_number'], name='accounts_ac_nid_num_f3cdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['application_number'], name='accounts_ac_applica_b8d079_idx'),
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['account_number'], name='accounts_ac_account_2845cd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['status', 'application_date'], name='accounts_ac_status_6dad6c_idx'),
        ),
    ]
