# Generated by Django 4.2.7 on 2026-07-11 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('account_title_Bng', models.CharField(max_length=255)),
                ('account_title_Eng', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('SAVINGS', 'সঞ্চয়ী'), ('CURRENT', 'চলতি'), ('SND', 'এসএনডি'), ('FC', 'এফসি'), ('RFCD', 'আরএফসিডি'), ('NFCD', 'এনএফসিডি'), ('OTHERS', 'অন্যান্য')], max_length=20)),
                ('currency_type', models.CharField(choices=[('BDT', 'টাকা'), ('EURO', 'ইউরো'), ('POUND', 'পাউন্ড'), ('USD', 'ডলার'), ('OTHERS', 'অন্যান্য')], max_length=20)),
                ('account_procedure_type', models.CharField(choices=[('SINGLE', 'এককভাবে'), ('COMBINED', 'যৌথভাবে'), ('ANY_ONE', 'যে কোনো একজন'), ('ANY_ONE_or_LIVING', 'যে কোনো একজন অথবা জীবিতজন'), ('OTHERS', 'অন্যান্য')], max_length=20)),
                ('initial_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('full_name_bng', models.CharField(max_length=200)),
                ('full_name_eng', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('resident_status', models.CharField(choices=[('RESIDENT', 'রেসিডেন্ট'), ('NON_RESIDENT', 'নন-রেসিডেন্ট')], max_length=30)),
                ('service', models.CharField(max_length=60)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('income_source', models.CharField(max_length=200)),
                ('TIN', models.CharField(blank=True, max_length=12, null=True)),
                ('pre_vill', models.CharField(blank=True, max_length=200, null=True)),
                ('pre_post_office', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_ps', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_district', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('pre_email', models.EmailField(blank=True, max_length=80, null=True)),
                ('per_vill', models.CharField(blank=True, max_length=200, null=True)),
                ('per_post_office', models.CharField(blank=True, max_length=50, null=True)),
                ('per_ps', models.CharField(blank=True, max_length=100, null=True)),
                ('per_district', models.CharField(blank=True, max_length=100, null=True)),
                ('per_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('per_email', models.EmailField(blank=True, max_length=80, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('other_doc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('other_number', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_doc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_DOB1', models.DateField(blank=True, null=True)),
                ('nominee_address1', models.TextField(blank=True, null=True)),
                ('nominee_relation1', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_nid1', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_percentage1', models.CharField(blank=True, max_length=15, null=True)),
                ('nominee_other_doc_name1', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_other_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_DOB2', models.DateField(blank=True, null=True)),
                ('nominee_address2', models.TextField(blank=True, null=True)),
                ('nominee_relation2', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_nid2', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_percentage2', models.CharField(blank=True, max_length=15, null=True)),
                ('nominee_other_doc_name2', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_other_number2', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_present_address3', models.TextField(blank=True, null=True)),
                ('nominee_permanent_address3', models.TextField(blank=True, null=True)),
                ('nominee_other_doc_name3', models.CharField(blank=True, max_length=200, null=True)),
                ('nominee_other_number3', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_relation3', models.CharField(blank=True, max_length=100, null=True)),
                ('nominee_phone3', models.CharField(blank=True, max_length=20, null=True)),
                ('debit_card', models.BooleanField(default=False)),
                ('debit_card_delivery_branch', models.CharField(blank=True, max_length=200, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.accountapplication')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['nid_number'], name='accounts_ac_nid_num_f3cdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['application_number'], name='accounts_ac_applica_b8d079_idx'),
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['account_number'], name='accounts_ac_account_2845cd_idx'),
        ),
        migrations.AddIndex(
            model_name='accountapplication',
            index=models.Index(fields=['status', 'application_date'], name='accounts_ac_status_6dad6c_idx'),
        ),
    ]
