# Generated by Django 4.2.7 on 2026-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountapplication',
            name='initial_deposit_in_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
