# Generated by Django 4.2.7 on 2026-07-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountapplication_initial_deposit_in_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountapplication',
            name='bc_number',
        ),
        migrations.RemoveField(
            model_name='accountapplication',
            name='pp_number',
        ),
    ]
