# Generated by Django 4.2.7 on 2026-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_accountapplication_bc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
