# Generated by Django 4.2.7 on 2026-07-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accountapplication_application_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountapplication',
            name='application_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
