# Generated by Django 4.2.7 on 2026-07-12 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WageEarnersBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=30, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('face_value_words', models.CharField(blank=True, max_length=500, null=True)),
                ('applicant_name', models.CharField(max_length=250)),
                ('nominee_name', models.CharField(blank=True, max_length=250)),
                ('applicant_address', models.TextField()),
                ('nominee_address', models.TextField(blank=True)),
                ('name_of_paying_office', models.CharField(max_length=250)),
                ('denomination', models.CharField(blank=True, choices=[('25000', '25,000'), ('50000', '50,000'), ('100000', '1,00,000'), ('200000', '2,00,000'), ('500000', '5,00,000'), ('1000000', '10,00,000'), ('5000000', '50,00,000')], max_length=20, null=True)),
                ('bonds_25000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonds_50000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonds_100000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonds_200000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonds_500000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonds_1000000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bonds_5000000', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_no_of_bonds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('FC_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('FC_account_office', models.CharField(blank=True, max_length=150, null=True)),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('service_address', models.CharField(blank=True, max_length=250, null=True)),
                ('reference_name', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_service', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_service_address', models.CharField(blank=True, max_length=250, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BondApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.wageearnersbond')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='wageearnersbond',
            index=models.Index(fields=['applicant_name'], name='bonds_wagee_applica_55902b_idx'),
        ),
        migrations.AddIndex(
            model_name='wageearnersbond',
            index=models.Index(fields=['status', 'application_date'], name='bonds_wagee_status_f35fbf_idx'),
        ),
    ]
