# Generated by Django 4.2.7 on 2026-07-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='total_no_of_bonds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
