# Generated by Django 4.2.7 on 2026-07-25 06:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0002_remove_wageearnersbond_total_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(max_length=30, unique=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('bond_type', models.CharField(blank=True, max_length=150, null=True)),
                ('stabond_typetus', models.CharField(blank=True, choices=[('US DOLLAR INVESTMENT BOND', 'US DOLLAR INVESTMENT BOND'), ('US DOLLAR PREMIUM BOND', 'US DOLLAR PREMIUM BOND')], max_length=70, null=True)),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('face_value_words', models.CharField(blank=True, max_length=500, null=True)),
                ('applicant_name', models.CharField(max_length=250)),
                ('nominee_name', models.CharField(blank=True, max_length=250, null=True)),
                ('applicant_address_abroad', models.TextField(blank=True, null=True)),
                ('applicant_address_BD', models.TextField(blank=True, null=True)),
                ('nominee_address', models.TextField(blank=True)),
                ('applicant_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('nominee_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('relation_with_nominee', models.CharField(blank=True, max_length=150, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('FC_account_no', models.CharField(blank=True, max_length=20, null=True)),
                ('FC_account_office', models.CharField(blank=True, max_length=150, null=True)),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('service_address', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_paying_office', models.CharField(max_length=250)),
                ('address_of_paying_office', models.CharField(blank=True, max_length=255, null=True)),
                ('denomination', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='denomination',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='USDBondApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonds.usdbond')),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='usdbond',
            index=models.Index(fields=['applicant_name'], name='bonds_usdbo_applica_840163_idx'),
        ),
        migrations.AddIndex(
            model_name='usdbond',
            index=models.Index(fields=['status', 'application_date'], name='bonds_usdbo_status_aefdf5_idx'),
        ),
    ]
