# Generated by Django 4.2.7 on 2026-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_usdbond_alter_wageearnersbond_denomination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usdbond',
            name='stabond_typetus',
        ),
        migrations.AddField(
            model_name='usdbond',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usdbond',
            name='bond_type',
            field=models.CharField(blank=True, choices=[('US DOLLAR INVESTMENT BOND', 'US DOLLAR INVESTMENT BOND'), ('US DOLLAR PREMIUM BOND', 'US DOLLAR PREMIUM BOND')], max_length=70, null=True),
        ),
    ]
