# Generated by Django 4.2.7 on 2026-07-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_remove_usdbond_stabond_typetus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usdbond',
            old_name='applicant_address_abroad',
            new_name='applicant_address',
        ),
    ]
