# Generated by Django 4.2.7 on 2026-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0005_rename_applicant_address_abroad_usdbond_applicant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
