# Generated by Django 4.2.7 on 2026-07-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0006_wageearnersbond_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='address_of_paying_office',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT')], default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='name_of_paying_office',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
