# Generated by Django 4.2.7 on 2026-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0007_wageearnersbond_address_of_paying_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageearnersbond',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT')], default='BDT', max_length=10),
        ),
    ]
