# Generated by Django 4.2.7 on 2026-07-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0008_alter_wageearnersbond_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='date_of_issue',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='place_of_issue',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
