# Generated by Django 4.2.7 on 2026-07-30 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0009_wageearnersbond_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdbond',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_USDB_app', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_WEB_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
