# Generated by Django 4.2.7 on 2026-07-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0010_alter_usdbond_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_100000',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_1000000',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_200000',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_25000',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_50000',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_500000',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='bonds_5000000',
        ),
    ]
