# Generated by Django 4.2.7 on 2026-07-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0011_remove_wageearnersbond_bonds_100000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageearnersbond',
            name='total_no_of_bonds',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
