# Generated by Django 4.2.7 on 2026-07-30 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0012_alter_wageearnersbond_total_no_of_bonds'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=18, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
