# Generated by Django 4.2.7 on 2026-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0013_wageearnersbond_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageearnersbond',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
    ]
