# Generated by Django 4.2.7 on 2026-08-01 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0015_bondapprovallog_usdbondapprovallog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wageearnersbond',
            old_name='FC_account_office',
            new_name='Bank_account_branch',
        ),
        migrations.RenameField(
            model_name='wageearnersbond',
            old_name='FC_account_no',
            new_name='Bank_account_no',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='address_of_paying_office',
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='Bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='applicant_address_abroad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='applicant_name_bn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='nid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='applicant_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='name_of_paying_office',
            field=models.CharField(choices=[('Wage Earners Corp br. Dhaka', 'Wage Earners Corp br. Dhaka'), ('Dhaka Cant.Corp br. Dhaka', 'Dhaka Cant.Corp br. Dhaka'), ('Wage Earners Corp br. Chattogram', 'Wage Earners Corp br. Chattogram'), ('Khulna Corp. br. Khulna', 'Khulna Corp. br. Khulna'), ('Dargagate Corp. br. Sylhet', 'Dargagate Corp. br. Sylhet')], default='Wage Earners Corp br. Dhaka', max_length=150),
        ),
        migrations.AlterField(
            model_name='wageearnersbond',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
