# Generated by Django 4.2.7 on 2026-08-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0016_rename_fc_account_office_wageearnersbond_bank_account_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='denomication_words',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
