# Generated by Django 4.2.7 on 2026-08-01 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0017_wageearnersbond_denomication_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageearnersbond',
            name='denomination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
