# Generated by Django 4.2.7 on 2026-08-01 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0018_alter_wageearnersbond_denomination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wageearnersbond',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=25000.0, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
