# Generated by Django 4.2.7 on 2026-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0019_alter_wageearnersbond_face_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='nominee_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='nominee_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='nominee_nid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='phone_abroad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
