# Generated by Django 4.2.7 on 2026-09-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0020_wageearnersbond_date_of_expiry_wageearnersbond_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='total_no_of_bonds',
        ),
    ]
