# Generated by Django 4.2.7 on 2026-09-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0021_remove_wageearnersbond_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wageearnersbond',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='usdbond',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='father_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='mother_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='beneficiary_father_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='beneficiary_mother_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='beneficiary_spouse_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_name_bn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_phone_abroad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='benificiary_present_address',
            field=models.TextField(blank=True),
        ),
    ]
