# Generated by Django 4.2.7 on 2026-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0022_remove_wageearnersbond_mobile_no_usdbond_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_father',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_mother',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_name_bn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_per_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='identifier_pre_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='minor_nominee_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='minor_nominee_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='relation_with_nominee',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='visa_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='visa_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wageearnersbond',
            name='visa_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
