# Generated by Django 4.2.7 on 2026-09-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0023_wageearnersbond_identifier_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wageearnersbond',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
