# Generated by Django 4.2.7 on 2026-09-29 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0024_wageearnersbond_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usdbond',
            old_name='applicant_contact',
            new_name='benificiary_phone_abroad',
        ),
        migrations.AddField(
            model_name='usdbond',
            name='applicant_name_bn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_father_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_mother_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_name_bn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_phone_bangladesh',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='benificiary_spouse_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='nid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='nominee_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='nominee_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='nominee_nid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='phone_abroad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='relation_with_holder',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='visa_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='visa_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='visa_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usdbond',
            name='denomination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usdbond',
            name='face_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usdbond',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
