# Generated by Django 4.2.7 on 2026-09-29 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0025_rename_applicant_contact_usdbond_benificiary_phone_abroad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdbond',
            name='identifier_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_father',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_mother',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_name_bn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_per_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='identifier_pre_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='is_minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='minor_nominee_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usdbond',
            name='minor_nominee_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='usdbond',
            name='relation_with_nominee',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
