# Generated by Django 4.2.7 on 2026-09-29 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0026_usdbond_identifier_dob_usdbond_identifier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdbond',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
